const SHORT_TIME = 40;
const SMALL_SCREEN = 500;
const MIDDLE_SCREEN = 1276;
const BIG_LINE = 3;
const SMALL_LINE = 2;
const BIG_VISIBLE = 12;
const MIDDLE_VISIBLE = 8;
const SMALL_VISIBLE = 5;

export { SHORT_TIME, SMALL_SCREEN, MIDDLE_SCREEN, SMALL_LINE,
       BIG_LINE, BIG_VISIBLE, MIDDLE_VISIBLE, SMALL_VISIBLE }